# .github/workflows/ci-cd.yml
name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip 
        pip install pytest
      

    - name: Run tests with pytest
      run: |
        pytest todo-test.py

        - name: Set up Docker Buildx
          uses: docker/setup-buildx-action@v2

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_USERNAME }}  # Store Docker Hub credentials in GitHub Secrets
        password: ${{ secrets.DOCKER_PASSWORD }}  # Store Docker Hub credentials in GitHub Secrets

    - name: Build Docker image
      run: |
        docker build -t ashsaid/todolist:latest .
      
    - name: Push Docker image
      run: |
        docker push ashsaid/todolist:latest

