# .github/workflows/ci-cd.yml
name: Python CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.10]

    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v2
      with:
        python-version: ${{ matrix.python-version }}
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install flake8 pytest pytest-cov bandit
        
    - name: Lint with flake8
      run: |
        flake8 . --count --max-line-length=100 --statistics
        
    - name: Security check with bandit
      run: |
        bandit -r . -c pyproject.toml

    - name: Run tests with pytest
      run: |
        pytest tests/ --cov=. --cov-report=xml
